apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ual4vx3ib-python
  janus-idp.io/tekton: ual4vx3ib-python
  backstage.io/kubernetes-id: ual4vx3ib-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ual4vx3ib-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
