apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ual4vx3ib-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ual4vx3ib-python 
  name: ual4vx3ib-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ual4vx3ib-python 
